Custom template for config resource
sous-chefs/apache2 pull request #717
Opened 2020-09-18 02:08 UTC by limitusus

# Description

Enable to specify template cookbook for config resource.

Specifically, I want to modify `ErrorLog` directive to pipe, not file.
Current `apache2.conf.erb` can't express such case, so I thought I should prepare an original template for that in my wrapper cookbook, but`apache2_config` resource has `cookbook` with 'apache2' hard-coded.
I think there is no reason not to let it configurable like `apache2_conf`, `apache_default_site` and so on.

## Issues Resolved

N/A

## Check List

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2020-09-18 02:09 UTC, kitchen-porter commented
<!--
  1 Error: Please include a CHANGELOG ent...
  1 Warning: This Pull Request is probably ...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-18 16:44 UTC, ramereth commented
@limitusus can you please add a changelog entry and maybe some new tests?

2020-09-20 03:13 UTC, limitusus commented
Added unit test. Is that enough or the same for integration test required?

2020-09-21 17:21 UTC, ramereth approved these changes
This LGTM as-is.

2020-09-21 17:57 UTC, ramereth requested changes
Can you please resolve the conflicts?

2020-09-21 17:57 UTC, ramereth commented on spec/resources/config_spec.rb
> +        extend Apache2::Cookbook::Helpers
Now that I merged #705, can you please remove this line?

2020-09-22 17:11 UTC, ramereth submitted a review, later dismissed

2020-09-22 17:19 UTC, ramereth approved these changes

2020-09-22 17:19 UTC, merged