Add template_cookbook property
sous-chefs/apache2 pull request #727
Opened 2020-11-19 09:02 UTC by gagarinfan

# Description

Provide template_cookbook property to enable passing own template for httpd.conf/apache2.conf in apache2_install

## Issues Resolved

#726 

## Check List

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2020-11-19 09:03 UTC, kitchen-porter commented
<!--
  1 Error: Please include a CHANGELOG ent...
  1 Warning: This Pull Request is probably ...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-19 21:40 UTC, ramereth commented
@gagarinfan can you please update the resource documentation and also add a test case for this in one of the test recipes along with an InSpec test? Thanks!

2020-11-20 12:32 UTC, gagarinfan commented
@ramereth Done

2020-11-20 18:39 UTC, ramereth requested changes

2020-11-20 18:39 UTC, ramereth commented on kitchen.yml
> +   - name: default
@gagarinfan can you please fix the indentation issue?

2020-11-20 19:26 UTC, Xorima approved these changes

2020-11-20 19:27 UTC, merged

2020-11-20 19:27 UTC, kitchen-porter commented
Released as: [8.7.0](https://github.com/sous-chefs/apache2/releases/tag/8.7.0)